spring.application.name=erp-saas-api

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=erp_inventcomvent;encrypt=false;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.username=sa
spring.datasource.password=Password123*

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# JWT
jwt.secret=erp-saas-super-secret-key-cambia-esto-en-produccion-min32chars
jwt.expiration-ms=86400000

api.sunat.token=sk_15589.yoOZCpuX9t9bsz3orwwJy4x3JbFLFu4A

app.uploads.directorio=uploads
app.uploads.url-base=http://localhost:8080/uploads